sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: DemonJoker0rHB98
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: AAAABBBBCCCCDDDDEEEEFFFF
    access-key-secret: AAAABBBBCCCCDDDDEEEEFFFFGGGGHHHH
    bucket-name: sky-take-out--yui
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wxAAAABBBBCCCCDDDD
    secret: AAAABBBBCCCCDDDDEEEEFFFFGGGGHHHH
    mchid: 1561414331
    mchSerialNo: AAAABBBBCCCCDDDDEEEEFFFFGGGGHHHHIIIIJJJJ
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php